
["Stat 7"]
	#Defines if the stat is on or off
	"Stat 7" = true
	#Defines which name do you want to use for this stat in the menu
	"Stat 7 Name " = "Pet HP"
	#Defines the ID of the attribute, example: minecraft:generic.attack_speed
	"Stat 7 ID" = "modid:pet-heal"
	#The value added to the attribute per level
	"Stat 7 Value" = 0.1
	"Stat 7 Max" = 5.0
	"Max Stat 7" = 0.0

["Extra 1"]
	"Stat 7 Extra 1 Value" = 4.0
	"Stat 7 Extra 1 LVL Req" = 1.0
	"Stat 7 Extra 1 Max" = 10.0
	"Stat 7 Extra 1 ID " = "epicfight:staminar"

["Extra 2"]
	"Stat 7 Extra 2 ID" = "aaa:ddd"
	"Stat 7 Extra 2 Value" = 3.0
	"Stat 7 Extra 2 LVL Req" = 4.0
	"Stat 7 Extra 2 Max" = 33.0

["Extra 3"]
	"Stat 7 Extra 3 ID" = "aaaa:dd"
	"Stat 7 Extra 3 Value" = 33.0
	"Stat 7 Extra 3 LVL Req" = 4.0
	"Stat 7 Extra 3 Max" = 4.0

["Epic Fight Stamina"]
	"Epic Fight Default Stamina" = 16.0

