#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jul 02 13:05:41 UTC 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=BSL_v8.4.zip
enableShaders=true
