#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jul 06 14:38:39 UTC 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=BSL_v8.4.zip
enableShaders=false
